import { Projeto2D, ModeloOpcao } from './types';

export const initialProjetos: Projeto2D[] = [
  {
    id: 'proj-1',
    nome: 'Porta de vidro residencial',
    clienteNome: 'Roberto Almeida',
    clienteTelefone: '(11) 98765-4321',
    tipo: 'porta-vidro',
    modelo: 'Pivotante com Bandeira',
    largura: 1.60,
    altura: 2.10,
    espessuraVidro: '10mm Temperado',
    corVidro: 'incolor',
    corPerfil: 'preto',
    puxador: 'tubular-60',
    dataAtualizacao: '22 Set 2024',
    status: 'aprovado',
    valorEstimado: 3450.00,
    observacoes: 'Instalação na entrada principal. Puxador inox preto fosco 60cm, ferragem pivotante superior e inferior com mola de piso.'
  },
  {
    id: 'proj-2',
    nome: 'Box de Banheiro Elegance',
    clienteNome: 'Mariana Costa',
    clienteTelefone: '(11) 97654-3210',
    tipo: 'box-banheiro',
    modelo: 'Frontal Correr (1F + 1M)',
    largura: 1.40,
    altura: 1.90,
    espessuraVidro: '8mm Temperado',
    corVidro: 'incolor',
    corPerfil: 'inox',
    puxador: 'concha',
    dataAtualizacao: '20 Set 2024',
    status: 'apresentado',
    valorEstimado: 1890.00,
    observacoes: 'Suíte master. Roldanas aparentes estilo elegance em aço inox escovado e vedação inferior em silicone.'
  },
  {
    id: 'proj-3',
    nome: 'Janela 4 Folhas Suprema',
    clienteNome: 'Condomínio Grand Village',
    clienteTelefone: '(11) 96543-2109',
    tipo: 'janela',
    modelo: 'Correr 4 Folhas (2 Fixas + 2 Móveis)',
    largura: 2.00,
    altura: 1.20,
    espessuraVidro: '8mm Temperado',
    corVidro: 'fume',
    corPerfil: 'preto',
    puxador: 'concha',
    dataAtualizacao: '18 Set 2024',
    status: 'aprovado',
    valorEstimado: 2600.00,
    observacoes: 'Linha Suprema na cor preta, fecho concha com trava automática e escovas de vedação acústica.'
  },
  {
    id: 'proj-4',
    nome: 'Portão Basculante Prime',
    clienteNome: 'Carlos Eduardo Santos',
    clienteTelefone: '(11) 95432-1098',
    tipo: 'portao-ferro',
    modelo: 'Basculante Tubular Horizontal',
    largura: 3.20,
    altura: 2.40,
    espessuraVidro: 'Sem vidro (Aço Galvanizado)',
    corVidro: 'incolor',
    corPerfil: 'preto',
    puxador: 'nenhum',
    dataAtualizacao: '15 Set 2024',
    status: 'rascunho',
    valorEstimado: 5800.00,
    observacoes: 'Portão em ferro tubular 50x20 com pintura eletrostática preta, caixa de contrapeso e social embutido.'
  },
  {
    id: 'proj-5',
    nome: 'Porta de Vidro 4 Folhas Varanda',
    clienteNome: 'Fernanda Lima',
    clienteTelefone: '(11) 94321-0987',
    tipo: 'porta-vidro',
    modelo: 'Correr 4 Folhas (2F + 2M)',
    largura: 3.60,
    altura: 2.20,
    espessuraVidro: '10mm Temperado',
    corVidro: 'incolor',
    corPerfil: 'branco',
    puxador: 'tubular-40',
    dataAtualizacao: '14 Set 2024',
    status: 'apresentado',
    valorEstimado: 6200.00,
    observacoes: 'Integração de sala com área gourmet. Trilho embutido no piso nivelado e fechadura bate-fecha.'
  },
  {
    id: 'proj-6',
    nome: 'Box de Canto em L Prime',
    clienteNome: 'Dr. Marcelo Pires',
    clienteTelefone: '(11) 93210-9876',
    tipo: 'box-banheiro',
    modelo: 'Canto em L (2F + 2M)',
    largura: 1.00,
    altura: 1.90,
    espessuraVidro: '8mm Temperado',
    corVidro: 'verde',
    corPerfil: 'dourado',
    puxador: 'concha',
    dataAtualizacao: '11 Set 2024',
    status: 'rascunho',
    valorEstimado: 2450.00,
    observacoes: 'Banheiro de hóspedes. Acabamento gold com amortecedor soft-close nas portas.'
  }
];

export const modelosPorTipo: Record<string, ModeloOpcao[]> = {
  'porta-vidro': [
    { id: 'porta-pivo', nome: 'Pivotante 1 Folha', descricao: 'Abertura pivotante moderna com mola de piso', tipo: 'porta-vidro' },
    { id: 'porta-pivo-bandeira', nome: 'Pivotante com Bandeira', descricao: 'Folha pivotante com vidro fixo superior', tipo: 'porta-vidro' },
    { id: 'porta-correr-2f', nome: 'Correr 2 Folhas (1F + 1M)', descricao: 'Uma folha fixa e uma folha móvel de correr', tipo: 'porta-vidro' },
    { id: 'porta-correr-4f', nome: 'Correr 4 Folhas (2F + 2M)', descricao: 'Duas folhas móveis centrais e duas fixas laterais', tipo: 'porta-vidro' },
  ],
  'janela': [
    { id: 'janela-correr-2f', nome: 'Correr 2 Folhas (1F + 1M)', descricao: 'Janela tradicional de duas folhas', tipo: 'janela' },
    { id: 'janela-correr-4f', nome: 'Correr 4 Folhas (2F + 2M)', descricao: 'Abertura central ampla com duas folhas corrediças', tipo: 'janela' },
    { id: 'janela-maximar', nome: 'Maxim-Ar Basculante', descricao: 'Projeção para fora com braço articulado', tipo: 'janela' },
    { id: 'janela-3-modulos', nome: '3 Módulos com Fixo Inferior', descricao: 'Duas folhas superiores e peitoril fixo', tipo: 'janela' },
  ],
  'box-banheiro': [
    { id: 'box-frontal-correr', nome: 'Frontal Correr (1F + 1M)', descricao: 'Painel fixo e porta deslizante com trilho', tipo: 'box-banheiro' },
    { id: 'box-canto-l', nome: 'Canto em L (2F + 2M)', descricao: 'Encontro em 90 graus para banheiros compactos', tipo: 'box-banheiro' },
    { id: 'box-abrir-pivo', nome: 'Porta de Abrir Pivotante', descricao: 'Sem trilho superior, dobradiças de aço', tipo: 'box-banheiro' },
  ],
  'portao-ferro': [
    { id: 'portao-basculante-tubular', nome: 'Basculante Tubular Horizontal', descricao: 'Barras tubulares horizontais com design limpo', tipo: 'portao-ferro' },
    { id: 'portao-gradil-vertical', nome: 'Gradil Vertical Moderno', descricao: 'Tubos verticais com vãos simétricos de segurança', tipo: 'portao-ferro' },
    { id: 'portao-veneziana', nome: 'Veneziana Fechada com Friso', descricao: 'Chapas fechadas para total privacidade', tipo: 'portao-ferro' },
  ]
};
